import Foundation

public class Word {
    public let body: [String: String] = [
        "heart": "❤️",
        "eyes": "👀",
        "tongue": "👅",
        "gloves": "🧤",
        "hand": "✋🏽",
        "nose": "👃🏽",
        "ear": "👂🏽",
        "mouth": "👄",
        "tooth": "🦷",
        "foot": "🦶🏽",
        "leg": "🦵🏼",
        "arm": "💪🏼"
    ]
    public let clothing: [String: String] = [
        "shoe": "👞",
        "pants": "👖",
        "shirt": "👕",
        "hat": "🧢",
        "kimono": "👘",
        "crown": "👑",
        "ring": "💍",
        "scarf": "🧣",
        "dress": "👗",
        "bag": "🎒",
        "socks": "🧦",
        "bikini": "👙",
        "glasses":"👓",
        "umbrella": "☂️"
    ]
    public let food: [String: String] = [
        "banana": "🍌",
        "apple": "🍎",
        "pear": "🍐",
        "peach": "🍑",
        "lemon": "🍋",
        "carrot": "🥕",
        "pizza": "🍕",
        "bread": "🍞",
        "taco": "🌮",
        "sushi": "🍣",
        "egg": "🥚",
        "coffee": "☕️",
        "popcorn": "🍿",
        "cheese": "🧀",
        "spoon": "🥄",
        "candy": "🍬",
        "grape": "🍇",
        "bacon": "🥓",
        "pancakes": "🥞"
    ]
    public let nature: [String: String] = [
        "fish": "🐟",
        "bear": "🐻",
        "dog": "🐶",
        "cat": "🐱",
        "monkey": "🐵",
        "tiger": "🐯",
        "cow": "🐮",
        "horse": "🐴",
        "pig": "🐷",
        "whale": "🐳",
        "ant": "🐜",
        "sun": "☀️",
        "star": "⭐️",
        "moon": "🌙",
        "cloud": "☁️",
        "fox": "🦊",
        "rabbit": "🐰",
        "mountain": "🏔",
        "sea": "🌊",
        "fire": "🔥",
        "flower": "🌸",
        "tree": "🌲"
    ]
    public let object: [String: String] = [
        "bus": "🚎",
        "car": "🚗",
        "ball": "⚽️",
        "clock": "⏰",
        "balloon": "🎈",
        "book": "📕",
        "key": "🔑",
        "hammer": "🔨",
        "money": "💵",
        "letter": "✉️",
        "pencil": "✏️",
        "bed": "🛏",
        "guitar": "🎸",
        "drum": "🥁",
        "anchor": "⚓️",
        "house": "🏠",
        "church": "⛪️"
    ]
    public let mixed: [String: String] = [
        "officer": "👮🏻‍♂️",
        "king": "🤴🏽",
        "queen": "👸🏽",
        "teacher": "👩🏼‍🏫",
        "farmer": "👨🏻‍🌾",
        "doctor": "👩🏻‍⚕️",
        "scientist": "👩🏽‍🔬",
        "artist": "👨🏽‍🎨",
        "wizard": "🧙🏽‍♂️",
        "mechanic": "👩🏽‍🔧",
        "chef": "👨🏽‍🍳",
        "happy": "😄",
        "smile": "😁",
        "cry": "😢",
        "love": "😍",
        "sleep": "😴",
        "kiss": "😚",
        "sick": "🤒",
        "sad": "☹️",
        "angry": "😡",
        "baby": "👶🏼",
        "man": "👨🏻",
        "woman": "👩🏽‍🦱"
    ]
    public init() {}
}
